### ISSUE TITLE
CAN communication support not available for STM32F746

### ISSUE THREAD

**Issue by Vicky-S** [stm32duino/Arduino_Core_STM32#259]
I could not find any example for CAN communication in STM32 official core. Is there any?

**Comment by fpistm** [comment]
Currently, there is no CAN support

**Comment by Vicky-S** [comment]
Ok. will it be available in future?

**Comment by fpistm** [comment]
Yes but I can't tell when...

**Comment by Vicky-S** [comment]
Ok... Please try to make support ASAP..

**Comment by Vicky-S** [comment]
Ok... Please try to make support ASAP..

**Comment by BennehBoy** [comment]
@fpistm, by no support you mean there is no library right?  So people could program directly against HAL  CAN modules?

**Comment by fpistm** [comment]
@BennehBoy 
Yes of course. All STM32 features are available thanks HAL/LL (if user enable the right HAL module).
All stuff which can be done thanks the cube are available. By no support I told about Arduino point of view, there is no dedicated library to support STM32 CAN for this core with specific Arduino API style

**Comment by jacky4566** [comment]
Bump. Would love to see some CAN bus support. Seems silly to buy a standalone SPI chip when all you need is a transceiver.

**Comment by fpistm** [comment]
Hi @jacky4566 
I'd love too. 
I know @geosmall made some work around CAN:
https://github.com/geosmall/UAVCAN-for-STM32-Arduino

**Comment by seeers** [comment]
Unfortunately the UAVCAN example only works with the STM32Duino version 1.4.
With version 1.8 I get the following errors:
`
sketch\can.c: In function 'MX_CAN_Init':
can.c:12: error: 'CAN_InitTypeDef' {aka 'struct <anonymous>'} has no member named 'SJW'
   12 |   hcan.Init.SJW = CAN_SJW_1TQ;
      |            ^
can.c:13: error: 'CAN_InitTypeDef' {aka 'struct <anonymous>'} has no member named 'BS1'
   13 |   hcan.Init.BS1 = CAN_BS1_1TQ;
      |            ^
can.c:14: error: 'CAN_InitTypeDef' {aka 'struct <anonymous>'} has no member named 'BS2'
   14 |   hcan.Init.BS2 = CAN_BS2_1TQ;
      |            ^
can.c:15: error: 'CAN_InitTypeDef' {aka 'struct <anonymous>'} has no member named 'TTCM'
   15 |   hcan.Init.TTCM = DISABLE;
      |            ^
can.c:16: error: 'CAN_InitTypeDef' {aka 'struct <anonymous>'} has no member named 'ABOM'
   16 |   hcan.Init.ABOM = DISABLE;
      |            ^
can.c:17: error: 'CAN_InitTypeDef' {aka 'struct <anonymous>'} has no member named 'AWUM'
   17 |   hcan.Init.AWUM = DISABLE;
      |            ^
can.c:18: error: 'CAN_InitTypeDef' {aka 'struct <anonymous>'} has no member named 'NART'
   18 |   hcan.Init.NART = DISABLE;
      |            ^
can.c:19: error: 'CAN_InitTypeDef' {aka 'struct <anonymous>'} has no member named 'RFLM'
   19 |   hcan.Init.RFLM = DISABLE;
      |            ^
can.c:20: error: 'CAN_InitTypeDef' {aka 'struct <anonymous>'} has no member named 'TXFP'
   20 |   hcan.Init.TXFP = DISABLE;
      |            ^
exit status 1
'CAN_InitTypeDef' {aka 'struct <anonymous>'} has no member named 'SJW'

`

Is there maybe an easy way to get it running with the current version?

**Comment by fpistm** [comment]
@seeers 
I think this is due to STM32F1 HAL update.
looking at the Release_Notes.html:
https://htmlpreview.github.io/?https://github.com/stm32duino/Arduino_Core_STM32/blob/master/system/Drivers/STM32F1xx_HAL_Driver/Release_Notes.html

From version V1.1.3 / 09-October-2018:

> HAL CAN update
> Fields of CAN_InitTypeDef structure are reworked:
> SJW to SyncJumpWidth, BS1 to TimeSeg1, BS2 to TimeSeg2, TTCM to TimeTriggeredMode, ABOM to AutoBusOff, AWUM to AutoWakeUp, NART to AutoRetransmission (inversed), RFLM to ReceiveFifoLocked and TXFP to TransmitFifoPriority
> HAL_CAN_Init() is split into both HAL_CAN_Init() and HAL_CAN_Start() API’s
> HAL_CAN_Transmit() is replaced by HAL_CAN_AddTxMessage() to place Tx Request, then HAL_CAN_GetTxMailboxesFreeLevel() for polling until completion.
> HAL_CAN_Transmit_IT() is replaced by HAL_CAN_ActivateNotification() to enable transmit IT, then HAL_CAN_AddTxMessage() for place Tx request.
> HAL_CAN_Receive() is replaced by HAL_CAN_GetRxFifoFillLevel() for polling until reception, then HAL_CAN_GetRxMessage()
> to get Rx message.
> HAL_CAN_Receive_IT() is replaced by HAL_CAN_ActivateNotification() to enable receive IT, then HAL_CAN_GetRxMessage()
> in the receivecallback to get Rx message
> HAL_CAN_Slepp() is renamed as HAL_CAN_RequestSleep()
> HAL_CAN_TxCpltCallback() is split into HAL_CAN_TxMailbox0CompleteCallback(), HAL_CAN_TxMailbox1CompleteCallback() and HAL_CAN_TxMailbox2CompleteCallback().
> HAL_CAN_RxCpltCallback is split into HAL_CAN_RxFifo0MsgPendingCallback() and HAL_CAN_RxFifo1MsgPendingCallback().
> More complete “How to use the new driver” is detailed in the driver header section itself.

It seems there is an `HAL_CAN_LEGACY_MODULE_ENABLED` which can be enabled to use the legacy one but `HAL_CAN_MODULE_ENABLED` have to be disabled.

**Comment by jacky4566** [comment]
If you look at the code in this project the Canbus registers are really not all that hard to use. Maybe 3 or 4 key regs. 
I got it working after working out some of the defined values. I am working on my own implementation for STM32L4 as part of a custom library. 

https://github.com/UBC-Solar/Firmware-v2/tree/master/Peripherals/CAN

**Comment by geosmall** [comment]
I have the Libcanard UAVCAN example mentioned above now up and running / verified on V1.8.
https://github.com/geosmall/UAVCAN-for-STM32-Arduino

As this library (https://github.com/UAVCAN/libuavcan) uses it's own low level access and does not use HAL/LL I only needed to fix the rename deltas so not too bad.

UAVCAN based CAN is gaining some traction in both Ardupilot (https://github.com/ArduPilot/ardupilot) and PX4 (https://github.com/PX4/Firmware) so I'm planning to stay on that path.

I will update my example project over the weekend and document on https://www.stm32duino.com/

**Comment by fpistm** [comment]
Thanks  @geosmall for the feedback.

You can also document on the wiki if you want.

**Comment by Vicky-S** [comment]
Will it work for STM32F4 Series too?

**Comment by seeers** [comment]
> If you look at the code in this project the Canbus registers are really not all that hard to use. Maybe 3 or 4 key regs.
> I got it working after working out some of the defined values. I am working on my own implementation for STM32L4 as part of a custom library.
> 
> https://github.com/UBC-Solar/Firmware-v2/tree/master/Peripherals/CAN

I got it running with parts of your code on an stm32f103c8t6. Thank you very much

**Comment by geosmall** [comment]
@Vicky-S I have exampl

> Will it work for STM32F4 Series too? @geosmall

I have examples for F103C8 (Bluepill) AND F303RE-NUCLEO I am updating.  They are all pretty close but the devil is in the datasheets :).  I can check on my NUCLEO-F411RE.

**Comment by geosmall** [comment]
> Will it work for STM32F4 Series too? @geosmall



> Thanks @geosmall for the feedback.
> 
> You can also document on the wiki if you want.

Ok I'll capture on the forum and then figure out how to contribute to wiki (another first for me so forgive my mistakes in advance I will fix as I go :)

**Comment by geosmall** [comment]
UAVCAN libcanard based CAN example updated for v1.8 here https://github.com/geosmall/UAVCAN-for-STM32-Arduino.

F1 preliminary coms testing completed so far.

**Comment by Vicky-S** [comment]
@geosmall 

> The CAN periperals are all pretty close but the devil is in the datasheets :).

> It would of course need an F4 variant with CAN peripheral (e.g. F405/7, F446, etc and not F401, F411...).

I have F446 Board. Please tell me about the required changes. Let me try.

**Comment by geosmall** [comment]
F103 Bluepill end-to-end CAN testing now complete.  ESC values input with UAVCAN GUI are sent over CAN bus to Bluepill node, which receives and re-transmits those same ESC values out over Serial.

I suggest further discussion move to the forum here.: https://www.stm32duino.com/viewtopic.php?f=10&t=99

**Comment by geosmall** [comment]
F103C8 and F303CC UAVCAN functional testing now completed for both examples.

**Comment by pazi88** [comment]
Is there any progress on CAN support for STM32? It would be really useful for many projects. The example code from @seeers for example would be enough for me currently, but I can seem to figure out how to use the PA11 and PA12 in stm32f103c8t6 instead of the PB8 and PB9 that the code does remapping of the pins. https://github.com/seeers/CAN-Bus-Arduino_Core_STM32

**Comment by fpistm** [comment]
@pazi88 
currently, there is no dedicated task for this on my side.

**Comment by orhaneee** [comment]
@pazi88 how did you edit the code in order to use PA11 and PA12?

**Comment by pazi88** [comment]
@orhaneee See the code in here: https://github.com/pazi88/8Ch-EGT I have included CAN code to mine, but you should be able to make that out. The register settings are slightly different depending what pins you want to use. That all is verified to work.

**Comment by nopnop2002** [comment]
@orhaneee 
How to remap CAN port for stm32f103:
https://github.com/nopnop2002/Arduino-STM32-CAN/tree/master/stm32f103

**Comment by pazi88** [comment]
@nopnop2002 Thanks for that! I have tried to figure out how to make CAN work on F4 too, but that will save lot of time.

**Comment by nopnop2002** [comment]
@pazi88 I am currently trying to send and receive complete interrupts but have not yet succeeded.

**Comment by Elektrik1** [comment]
Any progress on implementing Hardware CAN library?

**Comment by J-f-Jensen** [comment]
I have made a working CAN library based on libraries I have found. It should work both with can0 and can1 on devices with two CAN devices, but I have only tested it with CAN0. USB serial cannot be used together with the CAN library on stm32f103 bluepill devices. Link: https://github.com/J-f-Jensen/libraries

**Comment by fpistm** [comment]
Thanks for sharing @J-f-Jensen 
Maybe it could be a good candidate to add it as a built-in library or other.
Probably some update would be required to support all series but I guess 90% of the work is done. 👏

**Comment by lutfisan** [comment]
any CAN FD support for NUCLEO-G474RE?

**Comment by pazi88** [comment]
> I have made a working CAN library based on libraries I have found. It should work both with can0 and can1 on devices with two CAN devices, but I have only tested it with CAN0. USB serial cannot be used together with the CAN library on stm32f103 bluepill devices. Link: https://github.com/J-f-Jensen/libraries

Nice library, but what I can see it only works on F1. It fails to build on F4.

**Comment by J-f-Jensen** [comment]
What error do you get? I can be a issue with the hal config fileBr Jens 
-------- Oprindelig besked --------Fra: Pasi Kemppainen <notifications@github.com> Dato: 26.11.2020  14.13  (GMT+01:00) Til: stm32duino/Arduino_Core_STM32 <Arduino_Core_STM32@noreply.github.com> Cc: J-f-Jensen <jens@2stroke4fun.dk>, Mention <mention@noreply.github.com> Emne: Re: [stm32duino/Arduino_Core_STM32] CAN communication support (#259) 

I have made a working CAN library based on libraries I have found. It should work both with can0 and can1 on devices with two CAN devices, but I have only tested it with CAN0. USB serial cannot be used together with the CAN library on stm32f103 bluepill devices. Link: https://github.com/J-f-Jensen/libraries

Nice library, but what I can see it only works on F1. It fails to build on F4.

**Comment by pazi88** [comment]
> What error do you get? I can be a issue with the hal config fileBr Jens  -------- Oprindelig besked --------Fra: Pasi Kemppainen <notifications@github.com> Dato: 26.11.2020 14.13 (GMT+01:00) Til: stm32duino/Arduino_Core_STM32 <Arduino_Core_STM32@noreply.github.com> Cc: J-f-Jensen <jens@2stroke4fun.dk>, Mention <mention@noreply.github.com> Emne: Re: [stm32duino/Arduino_Core_STM32] CAN communication support (#259) I have made a working CAN library based on libraries I have found. It should work both with can0 and can1 on devices with two CAN devices, but I have only tested it with CAN0. USB serial cannot be used together with the CAN library on stm32f103 bluepill devices. Link: https://github.com/J-f-Jensen/libraries Nice library, but what I can see it only works on F1. It fails to build on F4. —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

For example there is no AFIO registers in F4. And there was some other errors too.

**Comment by fpistm** [comment]
Hi @pazi88 
Which F4 boards you used ? did you defined the `HAL_CAN_MODULE_ENABLED `?

https://github.com/stm32duino/wiki/wiki/HAL-configuration#hal-modules-configuration

**Comment by shaneyake** [comment]
Does anybody know of a library that will work with the HAL_FDCAN_MODULE_ENABLED?
@J-f-Jensen library is great but I can't get it to compile for my Nucleo-H743IZ2.
or is there a way to use HAL_CAN_MODULE_ENABLED with the Nucleo-H743IZ2?
Thanks

**Comment by pazi88** [comment]
@shaneyake The library only works for F1 series as far as I know, because that's the only one using AFIO for pin mapping. F4 andvothets have different way to map pins, so that's why it wont compile (as I mentioned above).

**Comment by seb43654** [comment]
any progress on this? would be very useful to have can support...

**Comment by pazi88** [comment]
> any progress on this? would be very useful to have can support...

You can use this library I created. Uses HAL drivers, hadware interrupts and it's easy yo use. Should work with every stm32 chip that is supported by stm32duino: https://github.com/pazi88/STM32_CAN

**Comment by pazi88** [comment]
I have been meaning to do some last modifications to that and maybe make a PR for that to be added in stm32core.

**Comment by seb43654** [comment]
Wow thanks @pazi88  will test tomorrow! Was previously using MBed but it is failing with high bus loads....

**Comment by fpistm** [comment]
> e last modifications to that and maybe make a PR for that to be added in stm32core. I have been personally used that with many projects communicating busy vehicle CAan busses and it works great (other ones I have found, have many problems).

Hi @pazi88, do not hesitate to male a PR or you can also share it as an Arduino library.

**Comment by pazi88** [comment]
> Wow thanks @pazi88 will test tomorrow! Was previously using MBed but it is failing with high bus loads....

Yes with other libraries available I also had problems with high bus loads, but with this one all seems fine, because both TX and RX side are interrupt based and the packets are gathered to buffers that have configurable size.

**Comment by pazi88** [comment]
> > e last modifications to that and maybe make a PR for that to be added in stm32core. I have been personally used that with many projects communicating busy vehicle CAan busses and it works great (other ones I have found, have many problems).
> 
> Hi @pazi88, do not hesitate to male a PR or you can also share it as an Arduino library.

It works already as Arduino library. But I'll do those additions I have been meaning to do and do a PR then.

**Comment by ChinaBurn** [comment]
There is a working Can instance here, but this is not a library, I have tested it to work and use it in production.
https://github.com/nopnop2002/Arduino-STM32-CAN
