### ISSUE TITLE
fatal error: wiring_private.h

### ISSUE THREAD

**Issue by acronis2000** [stm32duino/Arduino_Core_STM32#3032]
Hi !

I'm using the Adafruit_ST77xx library in my projects to work with the display, and it was working fine on the stm32 with the 2.12 kernel version. However, today I updated the kernel to version 3.0, and now I'm getting an error when compiling: 'Documents\Arduino\libraries\Adafruit_ST7735_and_ST7789_Library\Adafruit_ST77xx.cpp:30:10: fatal error: wiring_private.h: No such file or directory

Is there a way to fix this?

**Comment by fpistm** [comment]
Since 3.0.0 and #2879,  ArduinoCore-API has been deployed.  
So third party libraries using some internal headers have to be updated.
STM32 core version have to be used to handle this.
Example:
```
#if defined(STM32_CORE_VERSION) && (STM32_CORE_VERSION  <= 0x020C0000)
#include "wiring_time.h"
#else
#include "wiring.h"
#endif
```

**Comment by fpistm** [comment]
PR done on the third party library.
