### ISSUE TITLE
Reference to pgmspace.h starting with core 3.0.0

### ISSUE THREAD

**Issue by bittmanv** [stm32duino/Arduino_Core_STM32#3034]
Hi, 

I have project, which i can compile on 2.12.0 core, shared between L412 and G070 MCUs and it include multiple external libraries,  including in my case  FastCRC library

After update to 3.0.0 core compilation fails with error 

`/Users/vaclavbittmann/Documents/ArduinoSTM/libraries/FastCRC/src/FastCRC_tables.h:36:10: fatal error: avr/pgmspace.h: No such file or directory
   36 | #include <avr/pgmspace.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
`
My environment is 
Board selected Generic. L412KBT
Core 3.0.0
Other compilation parameters in default.

MacBookPro M1
Arduino IDE 2.3.6 

I haven't checked older cores, but i don't see pgmspace.h in current core.  

I have seen multiple libraries, which are using approach to handle pgmspace by similar way as FastCRC
Compilation on core 2.12 works fine without error. 

Are we still compatible with Arduino ?

Vaclav

**Comment by fpistm** [comment]
pgmspace.h is available in the cores/arduino/api/deprecated-avr-comp

To fix this issue a pgmspace.h have to be created in cores/arduino/avr to include the one from cores/arduino/api/deprecated-avr-comp

It should fix and kept compatibility.
